DemoMVC/Models/AutoData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoMVC.Models
{
	public static class AutoData
	{
        public static List<AutoModel> autolijst { get; set; } = new List<AutoModel>();
        public static void Create()
		{
            autolijst.Add(new AutoModel() {
                KilometerStand = 150000,
            Merk = "Toyota",
            Type = "Auris"
        });

            autolijst.Add(new AutoModel()
            {
                KilometerStand = 20,
                Merk = "BMW",
                Type = "109D"
            });
		}
		
    }
}

DemoMVC/Models/AutoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DemoMVC.Models
{
    public class AutoModel
    {
        public AutoModel()
        {
            autosCreated++;
        }
        private static int autosCreated = 0;
        public int Id { get; set; } = autosCreated;
        [Required(ErrorMessage = "Kilometerstand is verplicht!")]
        public int KilometerStand { get; set; }
        [Required(ErrorMessage ="Merk is verplicht!")]
        public string Merk { get; set; }
        [Required(ErrorMessage = "Type is verplicht!")]
        [MinLength(1,ErrorMessage ="De naam is te kort")]
        [MaxLength(20,ErrorMessage ="Too long")]
        public string Type { get; set; }
    }
}

DemoMVC/Models/ErrorViewModel.cs
using System;

namespace DemoMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoMVC/Controllers/AutoController.cs
using DemoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoMVC.Controllers
{
    public class AutoController : Controller
    {
        public IActionResult Index()
        {
            return View(AutoData.autolijst);
        }
        public IActionResult Detail(int id)
        {
            return View(AutoData.autolijst.Find(x => x.Id == id));
        }
        public IActionResult AddAuto()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddAuto(AutoModel auto)
        {
            if (ModelState.IsValid)
            {
                AutoData.autolijst.Add(auto);
                return RedirectToAction("Detail", new { id = auto.Id });
            }
            return View(auto);
        }
    }
}

DemoMVC/Controllers/HomeController.cs
using DemoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DemoMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Landigspagina";
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DemoMVC/Views/Auto/AddAuto.cshtml
@model AutoModel

<h1>Add a new Car to the list</h1>

@using (Html.BeginForm()) 
{
<div class="form-horizontal">
    <h4>Auto</h4>
    <hr />

    <div class="form-group">
        @Html.LabelFor(model => model.Merk, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Merk, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Merk,"",new { @class="text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Type, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KilometerStand, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KilometerStand, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.KilometerStand, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add Car" class="btn btn-default" />
        </div>
    </div>
</div>
}

DemoMVC/Views/Auto/Detail.cshtml
@model AutoModel

<h1>@Model.Merk - @Model.Type</h1>
<p>@Model.KilometerStand</p>

DemoMVC/Views/Auto/Index.cshtml
@model IEnumerable<AutoModel>

<table>
    <tr>
        <th>Merk</th>
        <th>Type</th>
        <th>Kmstand</th>
        <th>Details</th>
    </tr>
    @foreach (AutoModel autoModel in Model)
    {
        <tr>
            <td>@autoModel.Merk</td>
            <td>@autoModel.Type</td>
            <td>@autoModel.KilometerStand</td>
            <td>@Html.ActionLink("Go to Details","Detail","Demo",new { id=autoModel.Id }, new { @class="btn btn-primary" })</td>
        </tr>
    }
</table>
@Html.ActionLink("Add new Car", "AddAuto","Auto",null,new{@class="btn btn-primary"})

DemoMVC/Views/Home/Index.cshtml
<h1>@ViewData["title"]</h1>
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    @Html.ActionLink("Go to DemoIndex", "Index", "Auto", null, new { @class = "btn btn-primary btn-large" })

</div>

DemoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Demo" asp-action="Index" asp-route-id="5">DemoLink</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DemoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>